### ISSUE TITLE
Have the colors default to --primary-color, etc

### ISSUE THREAD

**Issue by tewalds** [PolymerElements/paper-slider#120]
Right now the defaults are --google-blue-700 and other hardcoded values. This makes changing the theme of a site much more tedious and tricky than if it was based on --primary-color, --primary-text-color, etc.

**Comment by keanulee** [comment]
Along the lines of https://github.com/PolymerElements/paper-button/issues/105, we would suggest that you use `paper-slider` specific styling. To avoid repeating the color definition, you could make that a variable and use it in multiple places:

``` css
:root {
  --primary-color: orange;

  --paper-slider-active-color: var(--primary-color);
  --paper-font-common-base: {
    color: var(--primary-color);
  }
}
```

This is arguably more code, but it gives the developer choice to style each element separately if needed.
