### ISSUE TITLE
Editable input for paper-slider is too short

### ISSUE THREAD

**Issue by lsuder** [PolymerElements/paper-slider#150]
On Polymer demo page (https://elements.polymer-project.org/elements/paper-slider?view=demo:demo/index.html&active=paper-slider) if you set the value to 255 the last number is partially covered by the up-down buttons.

The problem is even worse when the max value is above 1000. In such a case the last number is not visible at all.

Tested on Chrome 53.0.2785.101.

**Comment by davidptm56** [comment]
You can change input's style with `--paper-slider-input{}` mixin.

i.e.:

``` css
<style>
    ...
    paper-slider { --paper-slider-input: {width: 100px} }
    ...
</style>
```

**Comment by kriscooke** [comment]
As for the up-down arrows, I found them to be quite useless, so as of v1.1.21 of `PolymerElements/paper-input` you can hide the internal input's up-down arrows using the `--paper-input-container-input-webkit-spinner` mixin:
```css
paper-slider {
  --paper-input-container-input-webkit-spinner: {
    -webkit-appearance: none;
    margin: 0;
  };
}
```
