### ISSUE TITLE
Missing line-height for pin text

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-slider#173]
```css
paper-slider {
  line-height: normal;
}
```

https://jsfiddle.net/StartPolymer/y1w56395/
