### ISSUE TITLE
paper-slider only respects [dir=rtl] but not direction: ltr; in CSS nor nested [dir]

### ISSUE THREAD

**Issue by danbeam** [PolymerElements/paper-slider#190]
### Description

`paper-slider` added RTL support via `:host-context([dir="rtl"])` in https://github.com/PolymerElements/paper-slider/pull/181

This is super, except there are a few ways of changing text direction that it doesn't detect.

For example:

```css
paper-slider {
  direction: rtl;
}
```
or
```html
<html dir="rtl">
<paper-slider dir="ltr">
```

### Expected outcome
Slider's direction and effective text direction agree.

### Actual outcome
In some cases, the slider direction differs from the text direction.

### Live Demo
https://jsfiddle.net/7qxd7cjx/

### Steps to reproduce
1. plop `<paper-slider style="direction: rtl;">` or `<div dir=rtl><paper-slider dir=ltr>` onto a page
2. slide the knob

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

(Note: I assume this applies to all browsers but haven't actually checked).

/cc @dschuyler @keanulee

**Comment by takumif** [comment]
Am I right to assume that @danbeam will no longer be working on this bug? In that case, could someone else take over?
I want to force the sliders to be LTR in the [Cast dialog WebUI in Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=736954), and can do so with a local CSS workaround like the one below, but I'd be happier if such a workaround wasn't necessary.

```css
:host-context([dir="rtl"]) paper-slider[dir="ltr"] {
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
}
```
